project: Test
out_dir: testdata/run
star_tmp: ./tmp/
num_threads: 4
mem_limit: 8

sequence_files:
  file1:
    name: testdata/R1.fastq.gz
    base_definition:
      - cDNA(25-150)
      - UMI(12-19)
    find_pattern: "ATTGCGCAATG;2"
  file2:
    name: testdata/R2.fastq.gz
    base_definition:
      - cDNA(1-150)
  file3:
    name: testdata/I1.fastq.gz
    base_definition:
      - BC(1-10)
  file4:
    name: testdata/I2.fastq.gz
    base_definition:
      - BC(1-10)

reference:
  STAR_index: testdata/STARidx
  GTF_file: testdata/annot.gtf
  additional_files: null
  additional_STAR_params: "--limitBAMsortRAM 2000000000"

read_filtering:
  adapter_fasta: SmartSeq3xpressAdapter.fa
  quality: 20
  min_length: 20

filter_cutoffs:
  BC_filter:
    num_bases: 3
    phred: 20
  UMI_filter:
    num_bases: 3
    phred: 20

barcodes:
  index_table: testdata/cells_96.csv
  BarcodeBinning: 2
  nReadsperCell: 10

counting_opts:
  introns: true
  strand: 1
  downsampling: 0
  primaryHit: true
  multi_overlap: false
  fraction_overlap: 0

start_stage: Filtering
